version: 1.0.46.{build}
os: Previous Visual Studio 2015
configuration: Release
platform: x86
environment:
  certificatePass:
    secure: dJ2so3qs6OTWL1A7x8KOmA==
nuget:
  project_feed: true
before_build:
- ps: >-
    appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v3.2.0-rc/nuget.exe

    appveyor DownloadFile https://raw.githubusercontent.com/appveyor/ci/master/scripts/nuget-restore.cmd

    & ".\nuget-restore.cmd"

    $psw = ConvertTo-SecureString $env:certificatePass -AsPlainText -Force

    Import-PfxCertificate -FilePath .\PluralsightDownloader.Forms\Codecoding.pfx -CertStoreLocation cert:\CurrentUser\My -Password $psw
build:
  publish_wap: true
  verbosity: minimal
after_build:
- ps: msbuild PluralSightDownloader.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /t:Publish /p:ApplicationVersion="$env:APPVEYOR_BUILD_VERSION" /p:Platform="x86" /p:Configuration="Release" /verbosity:minimal
artifacts:
- path: PluralSightDownloader.Forms/bin/x86/Release/app.publish
  name: PluralsightDownloader.Forms
deploy:
- provider: FTP
  host: codecoding.com/codecoding.downloads/pluralsightdownloader/
  protocol: ftp
  username: Roberto
  password:
    secure: MA6Piny+7rJCRuNuXm05MA==
  artifact: PluralsightDownloader.Forms
  application: PluralsightDownloader.Forms
  on:
    branch: master
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  auth_token:
    secure: Q97tuoW1Nnx6Tjhzq9jYwQ==
  channel: '#github'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
